name: build_publish_docker_testing_images

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    # Just run it
  pull_request:
    branches:
      - 'main'
    paths:
      - 'testing/**'
  push:
    branches:
      - main
    paths:
      - 'testing/**'

jobs:
  publish-testing-image:
    strategy:
      matrix:
        image: ["testing-local-ssl-proxy"]

    runs-on: ubuntu-latest
    # runs-on: 4x150g-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_PKG_LOGIN }}
          password: ${{ secrets.GH_PKG_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: gh-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}

      - name: Build and push Docker image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: ./testing
          file: ./${{ matrix.image }}/Dockerfile
          push: true
          tags: ${{ steps.gh-meta.outputs.tags }}
