name: GCS Proxy

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    # Just run it
  push:
    branches:
      - main
    paths:
      - "gcs-proxy/**"

jobs:
  gcsproxy-image:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GCP Registry
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_DOCKER_KEY }}

      - uses: actions/checkout@v3

      - name: "GCS proxy image"
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./gcs-proxy
          tags: |
            us-central1-docker.pkg.dev/dfx-server/ci/gcs-proxy:latest

  deploy:
    needs: [gcsproxy-image]
    uses: infinity-swap/ci-wf/.github/workflows/deploy-cloud-run.yml@main
    with:
      gcp_project: dfx-server
      gcp_image_uri: us-central1-docker.pkg.dev/dfx-server/ci/gcs-proxy
      region: us-central1
      service: gcs-proxy

    secrets:
      gcp_deploy_token: ${{ secrets.GCP_DOCKER_KEY }}