name: GCS Proxy

on:
  workflow_dispatch:
    # Just run it
  push:
    branches:
      - main
      - 'CPROD-930'
    paths:
      - "gcs-proxy/Dockerfile"

jobs:
  gcsproxy-image:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GCP Registry
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_DOCKER_KEY }}

      - uses: actions/checkout@v3

      - name: "GCS proxy image"
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./gcs-proxy
          tags: |
            us-central1-docker.pkg.dev/dfx-server/ci/gcs-proxy:latest
