name: ic_dev_full_image

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    # Just run it
  push:
    branches:
      - main
    paths:
      - "ic-dev-full/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "ic-dev-full/**"

  workflow_run:
    workflows: [rust_dfx_base_image, ic_binaries]
    types: [completed]
    branches: [main]
env:
  BUILD_TAG: rust1.72-dfx0.15
  BASE_IMAGE: ghcr.io/${{ github.repository_owner }}/ic-dev-base:rust1.72-dfx0.15
  BIN_IMAGE: ghcr.io/${{ github.repository_owner }}/ic-bin:rc-2022-09-30

jobs:
  ic-full-image:
    if: ${{ ! github.event.workflow_run || (github.event.workflow_run.conclusion == 'success') }}
    runs-on: 4x150g-runner

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCP Registry
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_DOCKER_KEY }}

      - name: Login to Github Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_PKG_LOGIN }}
          password: ${{ secrets.GH_PKG_TOKEN }}

      - name: Checkout template repo
        uses: actions/checkout@v3

      - name: "Full image"
        uses: docker/build-push-action@v4
        with:
          push: ${{ (github.event_name != 'pull_request' && github.ref == 'refs/heads/main') ||  github.ref_type == 'tag' }}
          context: ./ic-dev-full
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            BIN_IMAGE=${{ env.BIN_IMAGE }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ic-dev-full:latest
            ghcr.io/${{ github.repository_owner }}/ic-dev-full:${{ env.BUILD_TAG }}
            us-central1-docker.pkg.dev/dfx-server/ci/ic-dev-full:latest
            us-central1-docker.pkg.dev/dfx-server/ci/ic-dev-full:${{ env.BUILD_TAG }}
