name: ic_binaries

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    # Just run it
  push:
    branches:
      - main
    paths:
      - "ic-bin/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "ic-bin/**"

env:
  BUILD_TAG: rc--2023-06-01
  IC_BUILD_BRANCH: patched-rc--2023-06-01_23-01

jobs:
  ic-binaries:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCP Registry
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_DOCKER_KEY }}

      - name: Login to Github Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_PKG_LOGIN }}
          password: ${{ secrets.GH_PKG_TOKEN }}

      - name: Checkout template repo
        uses: actions/checkout@v3

      - name: Building Dfinity nns tool and canisters wasms
        uses: docker/build-push-action@v4
        with:
          push: ${{ (github.event_name != 'pull_request' && github.ref == 'refs/heads/main') ||  github.ref_type == 'tag' }}
          context: ./ic-bin
          build-args: |
            IC_BUILD_BRANCH=${{ env.IC_BUILD_BRANCH }}
            BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/ic-dev-base:latest
          tags: |
            ghcr.io/${{ github.repository_owner }}/ic-bin:latest
            ghcr.io/${{ github.repository_owner }}/ic-bin:${{ env.BUILD_TAG }}
            us-central1-docker.pkg.dev/dfx-server/ci/ic-bin:latest
            us-central1-docker.pkg.dev/dfx-server/ci/ic-bin:${{ env.BUILD_TAG }}
