name: ic_binaries

on:
  workflow_dispatch:
    # Just run it
  push:
    branches:
      - main
    paths:
      - "ic-bin/**"

env:
  BUILD_TAG: latest

jobs:
  ic-binaries:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GCP Registry
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_DOCKER_KEY }}

      - name: Login to Github Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_PKG_LOGIN }}
          password: ${{ secrets.GH_PKG_TOKEN }}

      - name: Checkout template repo
        uses: actions/checkout@v3

      - name: Building Dfinity nns tool and canisters wasms
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./ic-bin
          build-args: |
            IC_BUILD_BRANCH=rebased-2022-02-17
            BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/ic-dev-base:latest
          tags: |
            ghcr.io/${{ github.repository_owner }}/ic-bin:latest
            ghcr.io/${{ github.repository_owner }}/ic-bin:${{ env.BUILD_TAG }}
            us-central1-docker.pkg.dev/dfx-server/ci/ic-bin:latest
            us-central1-docker.pkg.dev/dfx-server/ci/ic-bin:${{ env.BUILD_TAG }}
